default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: volunteer-api_development

test:
  <<: *default
  database: volunteer-api_test
  
production:
  <<: *default
  database: volunteerapi
