default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: volunteer-api_development

test:
  <<: *default
  database: volunteer-api_test
  
production:
  <<: *default
  database: volunteer-api_production
  username: volunteer-api
  password: <%= ENV['VOLUNTEER-API_DATABASE_PASSWORD'] %>
